import Foundation
import OpenAPIRuntime

/// Clean names for the generated control-plane DTOs.
///
/// The generator nests everything under `Components.Schemas.*`. Aliasing here
/// means UI code says `LoopState`, and a future generator rename lands in one
/// file instead of across every view.
///
/// Everything in this file is a *wire* type: the spec owns its shape, it carries
/// no behaviour, and it is regenerated by `Tools/generate.sh`. Where a type needs
/// behaviour it gets an extension below — never a parallel hand-written struct,
/// because two decoders for one wire format is exactly the drift this layout
/// exists to prevent.
///
/// The one shape deliberately absent is `Param`. The spec types it only under
/// `SettingsScope.fields`, while `JobInfo.params` and `Registry.modules[]`
/// deliver the same thing as untyped JSON — so it is hand-written in
/// `Param.swift` and serves all three. `Tools/normalize_spec.py` removes the
/// generated version so there is only ever one decoder for it.

// MARK: - Pairing

public typealias Health = Components.Schemas.Health
public typealias WhoAmI = Components.Schemas.WhoAmI

extension Health {
    public var isOK: Bool { status == "ok" }

    /// Guards against pointing the app at some *other* service that happens to
    /// answer on :8100 — a plausible mistake when typing a LAN address by hand.
    public var isWindex: Bool { service == "windex" }

    /// Whether the backend has a write token configured. Absent means no.
    public var needsToken: Bool { authRequired ?? false }
}

// MARK: - Operations

public typealias LoopState = Components.Schemas.LoopState
public typealias LoopsState = Components.Schemas.LoopsState
public typealias JobInfo = Components.Schemas.JobInfo
public typealias ActivityItem = Components.Schemas.ActivityItem
public typealias ScheduleEntry = Components.Schemas.ScheduleEntry
public typealias SourceFreshness = Components.Schemas.SourceFreshness
public typealias DatasetStats = Components.Schemas.DatasetStats
public typealias TimeseriesPoint = Components.Schemas.TimeseriesPoint
public typealias WorkersState = Components.Schemas.WorkersState
public typealias ControlState = Components.Schemas.ControlState
public typealias ThrottleState = Components.Schemas.ThrottleState
public typealias ActionResult = Components.Schemas.ActionResult
public typealias RecentDoc = Components.Schemas.RecentDoc
public typealias SearchMetrics = Components.Schemas.SearchMetrics

// MARK: - Logs

public typealias LogSource = Components.Schemas.LogSource
public typealias LogTail = Components.Schemas.LogTail

// MARK: - Crawl

public typealias CrawlRun = Components.Schemas.CrawlRun
public typealias CrawlRunDetail = Components.Schemas.CrawlRunDetail
public typealias CrawlRunList = Components.Schemas.CrawlRunList
public typealias CrawlStart = Components.Schemas.CrawlStart
public typealias CrawlQueued = Components.Schemas.CrawlQueued
public typealias CrawlCancelled = Components.Schemas.CrawlCancelled

// MARK: - Recipes

public typealias Registry = Components.Schemas.Registry
public typealias Recipe = Components.Schemas.Recipe
public typealias RecipeList = Components.Schemas.RecipeList
public typealias RecipeTasks = Components.Schemas.RecipeTasks
public typealias MarketplaceEntry = Components.Schemas.MarketplaceEntry
public typealias MarketplaceList = Components.Schemas.MarketplaceList
public typealias ValidationReport = Components.Schemas.ValidationReport
public typealias RecipeRun = Components.Schemas.RecipeRun
public typealias RecipeRunTask = Components.Schemas.RecipeRunTask
public typealias RecipeRunList = Components.Schemas.RecipeRunList
public typealias RecipeRunQueued = Components.Schemas.RecipeRunQueued
public typealias RecipeRunEvents = Components.Schemas.RecipeRunEvents

// MARK: - Bridging the generator's untyped containers

extension OpenAPIObjectContainer {
    /// Re-decode an open container as a concrete type.
    ///
    /// The generator represents `additionalProperties: true` and untyped objects
    /// as `OpenAPIObjectContainer`, which is a `[String: (any Sendable)?]` and
    /// can't be `Decodable`-ed directly. Round-tripping through JSON is the
    /// supported way back to a typed value, and it is how `JobInfo.params` and
    /// `Registry.modules[]` become `Param`s.
    public func decode<T: Decodable>(_ type: T.Type = T.self) throws -> T {
        do {
            let data = try JSONEncoder().encode(self)
            return try JSONDecoder().decode(T.self, from: data)
        } catch {
            throw WindexError.decoding(underlying: error)
        }
    }
}

extension ActionResult {
    /// A mutating call's acknowledgement carries only `ok`/`detail` in common —
    /// each action returns the state it just set, so the interesting keys land in
    /// `additionalProperties`. These read the ones the server actually sends.

    /// What was started, e.g. `"ccnews-sync"` (`{"started": name, "pid": N}`).
    public var started: String? {
        additionalProperties.value["started"] as? String
    }

    /// The pid of a detached process, for the actions that spawn one. Its
    /// presence means *accepted*, not *finished*.
    public var pid: Int? {
        additionalProperties.value["pid"] as? Int
    }

    /// Whether the loop/ingest toggle landed on, for the desired-state calls.
    public var enabled: Bool? {
        additionalProperties.value["enabled"] as? Bool
    }

    /// The source a loop or ingest toggle applied to.
    public var source: String? {
        additionalProperties.value["source"] as? String
    }

    /// The resulting state, e.g. `"up"` / `"disabled"`.
    public var state: String? {
        additionalProperties.value["state"] as? String
    }

    /// Whichever key this action reports, for a generic confirmation message.
    public var summary: String {
        detail ?? started ?? state ?? (ok == true ? "ok" : "done")
    }
}

extension JobInfo {
    /// This job's arguments as form controls.
    ///
    /// `params` is untyped in the spec but is `Param.describe()` on the wire —
    /// the same shape settings use, which is the point of `Param` being generic.
    /// Job params come back with `enforce: "reject"`, so the form must refuse
    /// out-of-range input rather than clamping it.
    ///
    /// An all-open object generates as a wrapper holding a single
    /// `additionalProperties` container, so the payload is unwrapped before the
    /// round-trip.
    public func parameters() throws -> [String: Param] {
        try params?.additionalProperties.decode([String: Param].self) ?? [:]
    }
}

extension RecipeRun {
    /// The frozen runtime config used to create this run.
    public func parameters() throws -> [String: JSONValue] {
        try params?.additionalProperties.decode([String: JSONValue].self) ?? [:]
    }

    public var isTerminal: Bool {
        ["succeeded", "failed", "cancelled"].contains(state)
    }
}
